### PR TITLE
Tech Stacks updated

### PR DESCRIPTION
**Pull request by Ansh101112**
Added required tech Stacks for the development of application.

### CODE REVIEW

**Comment by sanjay-kv** [comment]
image
Why is this even level 2? Let me know any background work gone through it, these need to mention on the issue page. 

As a reviewer I come here all I can see is readme changes, which makes me doubt and system is automatically flagging your contribution. Ideally this shouldn't be the case.

**Comment by Ansh101112** [comment]
> image
> Why is this even level 2? Let me know any background work gone through it, these need to mention on the issue page. 
> 
> As a reviewer I come here all I can see is readme changes, which makes me doubt and system is automatically flagging your contribution. Ideally this shouldn't be the case.

Yup sir the backend integration and new tech stacks are used in it that push to the backend repo codebase as well that's why.

**Comment by sanjay-kv** [comment]
you need to attach the respective PR link  in this.

**Comment by Ansh101112** [comment]
@sanjay-kv sirr please provide the specific label to this PR as it contains the TWILIO setup config code in it and other notification settings for the project that you can see the code in backend repo as well

**Comment by sanjay-kv** [comment]
Mate, 
you have to provide me the links to the respective work done here, 
image

I'm not sure why its hard to understand me. 

Im not claiming you doing spam work, As a reviewer and any other contributor see this PR, for them those Readme file is your work. Even if you have developed any server on different repo you have to mention in the PR link. 

image

As a reviewer all I can see is level2 assigned to this changes. 

+ you telling me on all the issue that you have done backend work, but all I'm asking is give the work proof over here. Issue solved. 

I will check those work is anyhow related to the `tech stack updated` PR which is this one with my technical team. 

Else it will be counted as spam.

**Comment by Ansh101112** [comment]
> Mate, @Ansh101112 
> you have to provide me the links to the respective work done here, 
> image
> 
> I'm not sure why its hard to understand me. @usha-madithati 
> 
> Im not claiming you doing spam work, As a reviewer and any other contributor who  see this PR, for them those Readme file is your work. Even if you have developed any server on different repo you have to mention in the PR link. 
> 
> image
> 
> As a reviewer all I can see is level2 assigned to this changes. 
> 
> + you telling me on all the issue that you have done backend work, but all I'm asking is give the work proof over here. Issue solved. 
> 
> I will check those work is anyhow related to the `tech stack updated` PR which is this one with my technical team. 
> 
> Else it will be counted as spam. 
> 
> 
> 

Here's the work proof: 
1) https://github.com/Ansh101113/SmartServer/blob/master/_tests_%2Fserver.test.js
2) https://github.com/Ansh101113/SmartServer/commit/95444657878b2d34b1c1397ab41a53ad25f429fe
3) https://github.com/Ansh101113/SmartServer/commit/0a31f9d1a2e0b4c5bd214525ae1690fb72202bd1

And more history work can be found on the repo.

**Comment by sanjay-kv** [comment]
image
image

I will pass this to technical team. to understand whats happening on the server side. Even if you work on any deployment all the work should be combined getting level3 (45 points is for that reason). 

You are the only one pointed out same issue in other people repository. 

I will review with technical team and get back to you.

**Comment by usha-madithati** [comment]
> image
> image
> 
> I will pass this to technical team. to understand whats happening on the server side. Even if you work on any deployment all the work should be combined getting level3 (45 points is for that reason). 
> 
> You are the only one pointed out same issue in other people repository. 
> 
> I will review with technical team and get back to you.
> 

Ok sir .@sanjay-kv

**Comment by sanjay-kv** [comment]
> @sanjay-kv sirr please provide the specific label to this PR as it contains the TWILIO setup config code in it and other notification settings for the project that you can see the code in backend repo as well

image

I found your another PR on twilio so whats this level3 for.?

**Comment by Ansh101112** [comment]
> > @sanjay-kv sirr please provide the specific label to this PR as it contains the TWILIO setup config code in it and other notification settings for the project that you can see the code in backend repo as well
> 
> image
> 
> I found your another PR on twilio so whats this level3 for.?

Sir the full twilio setup having bugs and all so it happens in part wise that's why

**Comment by sanjay-kv** [comment]
So you were telling me level3 for this current PR and level 3 for the above Twilo setup: 
Total 90 points just to setup Twilo.

**Pull request merged**
