### PR TITLE
Announcement Feat Added

### PR DESCRIPTION
**Pull request by Ansh101112**
### Description:
This PR contains the frontend and backend setup for announcing new features or telling users any info.

### Issue:
#381 

### Screenshots:
Screenshot (199)

### Reviewers:
@usha-madithati @sanjay-kv 

### NOTE:
This PR is under GSSOC'24

### CODE REVIEW

**Comment by usha-madithati** [comment]
@Ansh101112 will the users recive those announcements to their registered email address . Did you add that feature in your backend code

**Comment by Ansh101112** [comment]
> @Ansh101112 will the users recive those announcements to their registered email address . Did you add that feature in your backend code 

Yeah ma'am

**Comment by usha-madithati** [comment]
> > @Ansh101112 will the users recive those announcements to their registered email address . Did you add that feature in your backend code 
> 
> Yeah ma'am 
Ok then provide an output video regarding that .I will check and merge your pr @Ansh101112

**Comment by Ansh101112** [comment]
> > > @Ansh101112 will the users recive those announcements to their registered email address . Did you add that feature in your backend code 
> > 
> > Yeah ma'am 
> Ok then provide an output video regarding that .I will check and merge your pr @Ansh101112 

Ma'am please see the deployment of checks it's working fine. It's not possible for me to create video rn as the email comes on my same phone from which it is video making.

**Comment by usha-madithati** [comment]
Yeah I have seen the code files . I will merge

**Comment by usha-madithati** [comment]
Screenshot (207)


@Ansh101112 even after merging your pr i see no changes . So please do check on the server side. This is the reason why i have asked you to send me the images of swnding emails to users.

**Comment by Ansh101112** [comment]
> Screenshot (207)
> 
> 
> @Ansh101112 even after merging your pr i see no changes . So please do check on the server side. If it's working fine on your pc then I will check again after some time because the code files are correct so let me see after some time .

Ma'am I have checked it's working fine please logout and login again maybe some bug come due to this.

**Pull request merged**
