### PR TITLE
Updated links for live chat and customer Review

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
Updated.
@usha-madithati Please Review it soon

### CODE REVIEW

**Comment by usha-madithati** [comment]
> Updated.
> @usha-madithati Please Review it soon
> Yeah I will check

**Comment by Saipradyumnagoud** [comment]
> > Updated.
> > @usha-madithati Please Review it soon
> > Yeah I will check

Yes .. Let me know for any more changes

**Comment by Saipradyumnagoud** [comment]
@usha-madithati  can you please let me know for any changes

**Comment by usha-madithati** [comment]
I haven't merged it yet so if any changes are needed I will text you . I will merge it asap

**Comment by Saipradyumnagoud** [comment]
> I haven't merged it yet so if any changes are needed I will text you . I will merge it asap 

yes waiting for it to be merged @usha-madithati

**Comment by usha-madithati** [comment]
Sorry for the delay @Saipradyumnagoud 
I will check it asap for sure I will do it today .

**Comment by usha-madithati** [comment]
@Saipradyumnagoud Heyy ,Hii I have viewed your pr the live chat link isnt enabled ,make sure that its working fine.  If you fic I will change the level. Thank You.

**Comment by Saipradyumnagoud** [comment]
@usha-madithati Yes I am Working

**Comment by usha-madithati** [comment]
Ok

**Pull request merged**
