### PR TITLE
Announcement Feat. Added

### PR DESCRIPTION
**Pull request by Ansh101112**
### Description:
This PR contains the frontend and backend setup for announcing new features or telling users any info.

### Reviewers:
@usha-madithati @sanjay-kv 

### NOTE:
This PR is under GSSOC'24

### CODE REVIEW

**Comment by sanjay-kv** [comment]
Where is the issue link, try adding output image as well. 

So it would be better admin to review .

**Comment by usha-madithati** [comment]
> Where is the issue link, try adding output image as well. 
> 
> So it would be better admin to review . 

Thats what iam asking him sir. I haven't even created issue regarding that and he is ready with the pr I told him about the issue and he told that he has exams going on so he needs some time , and because of that I haven't raised issued. He didn't even told me that he is working on that issue now. I have been taking this with him sir.

**Comment by Ansh101112** [comment]
> Where is the issue link, try adding output image as well. 
> 
> So it would be better admin to review . 

Okay sir actually I forgot to add the issue link raising again pr with the issue badge if @usha-madithati PA has created.

**Comment by usha-madithati** [comment]
> > Where is the issue link, try adding output image as well. 
> > 
> > So it would be better admin to review . 
> 
> Okay sir actually I forgot to add the issue link raising again pr with the issue badge if @usha-madithati PA has created.

@Ansh101112 you can check i have created the issue

**Pull request closed without merging**
