### PR TITLE
Auth Line updated

### PR DESCRIPTION
**Pull request by Ansh101112**
### Description:
Fixed the bug in auth line of authentication in application.

## Reviwer:
@usha-madithati 

## Note:
This PR is under GSSOC'24.

### CODE REVIEW

**Comment by sanjay-kv** [comment]
@Ansh101112 

image
Leaderboard automatically detected some spams. 

Again this spams is because of frequent documentation updates beyond the developments. 
I understand docs update is important. but when it become frequent it will come under spams. 

@usha-madithati I can only validate this particular PR based on the Code changes , I'm pretty sure there is backend code for this and level has been already give. i sent you linkedin message regarding other issues with this repo + add me back to the repos. so I can correct the labels when I review.

**Comment by usha-madithati** [comment]
Yes sir I have checked that and I will give access to you for repo asap

**Comment by Ansh101112** [comment]
> @Ansh101112 
> 
> image
> Leaderboard automatically detected some spams. 
> 
> Again this spams is because of frequent documentation updates beyond the developments. 
> I understand docs update is important. but when it become frequent it will come under spams. 
> 
> @usha-madithati I can only validate this particular PR based on the Code changes , I'm pretty sure there is backend code for this and level has been already give. i sent you linkedin message regarding other issues with this repo + add me back to the repos. so I can correct the labels when I review. 

Hello sir,
Sir I am the contributor in this project and built it from the scratch using the MERN stack. 
Sir I believe that you have seen the work that I have done with this project and also see the code that I have written by this point of time. 
Also sir as per you said that I am getting more levels please do check that all given badges to me are accurate and given on the required that are of the respective level prs. 
And sir the prs regarding the docs update see those docs are important and as I have updated the docs frequently so that no delay and latency work will be shown to PA @usha-madithati regarding these small tasks. 
And also each and every PR are talked and well discussed with the PA @usha-madithati  and I have told her about each issues and prs that I am raising that are required in project. 
Also sir I am working on the another repo of this project that holds all the server credentials and all files of backend. That's why to give points all those my work on that pr I only demands the points coverage of that pr in this one that's why you have seen the level issues. 
And sir I am working on this project as of thinking of learning and making it from start as I have worked hard on this project to came out of this competition to ace it correctly not by spam or any other type of unethical ways. 
All prs code are here and all required ashes are too check the lines of code and the code that I have written on them then think of the changing the level badge sir.
Hope you understand.
Thank you.
@sanjay-kv

**Comment by sanjay-kv** [comment]
image
@Ansh101112 There is more concerns beyond that. 

This is second auth line PR, the before one you got level2 for admin change, This one is just a readme change with level3. 

- [ ] In opensource, especially in program like this it has been suggested to update the reademe respectively, if you cant do in single PR the next PR should be given level 1 or no levels. 

- [ ] Any background work you did should be highlighted in the PR or as commit history, even in big companies lot of changes happens at a single time. So without more detailed explanation of change, its gonna be quite hard to understand.

**Comment by Ansh101112** [comment]
> image
> @Ansh101112 There is more concerns beyond that. 
> 
> This is second auth line PR, the before one you got level2 for admin change, This one is just a readme change with level3. 
> 
> - [ ] In opensource, especially in program like this it has been suggested to update the reademe respectively, if you cant do in single PR the next PR should be given level 1 or no levels. 
> 
> - [ ] Any background work you did should be highlighted in the PR or as commit history, even in big companies lot of changes happens at a single time. So without more detailed explanation of change, its gonna be quite hard to understand. 
> 

Sir actually I have fixed the bug in backend repo that causing the server breakdown in render in this. That's why it's given level 3.

**Pull request merged**
