### PR TITLE
added nav bar for mobile display

### LINKED ISSUE #392: Feat: Mobile nav bar
### Describe the feature

Adding nav bar which can be assed in the mobile

### Add ScreenShots

image

You can see that for small screen displays  the nav bar is not so responsive

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
Made the Nav Bar Resposnive For the Mobile Screens Also 
i.e media (max-width: 768px)

closes #392

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@usha-madithati Please Review the pull Request soon.

**Comment by Saipradyumnagoud** [comment]
image

screenshot for Review

**Comment by usha-madithati** [comment]
Ok

**Comment by Saipradyumnagoud** [comment]
@usha-madithati can you please label it under gssoc 
And Level 3

**Comment by usha-madithati** [comment]
I will check your code files and if it's needed I will add

**Comment by Saipradyumnagoud** [comment]
> I will check your code files and if it's needed I will add 

okay @usha-madithati

**Pull request merged**
