### PR TITLE
Deployment added

### PR DESCRIPTION
**Pull request by Ansh101112**
Added a whole new deployment link with whole new updation. Also added a generic terms for adding stars on project repo.

### CODE REVIEW

**Comment by sanjay-kv** [comment]
@usha-madithati i would like to understand why this deployment level3.

**Comment by usha-madithati** [comment]
Sir the code had conflicts during the developments sir . A lot of conflicts have occured which has taken a lot time to resolve those conflicts. That's why only I have assigned level 3 sir.

**Comment by sanjay-kv** [comment]
Conflicts happens when new PR not able to merge on old files due to structure issue or improper pushing. 
It shouldn't be assigning more levels.

**Comment by Ansh101112** [comment]
> Conflicts happens when new PR not able to merge on old files due to structure issue or improper pushing. 
> It shouldn't be assigning more levels. 

Sir those are not the conflict happens with in the server files of code but it's happening in deployment issues that takes time to find out bugs and all thats why the level given to me is 3.

**Comment by usha-madithati** [comment]
@sanjay-kv 

Hi sir.
Good afternoon.
Sir I gave access to you for the repo sir . Please do accept the request and do the changes which you feel are necessary. And regarding spam I will reduce the prs of docs update sir after 1 succesful task only we will update the docs from now on sir . And assigning tasks to only 1 contributor iam also avoiding that sir. I have contacted new contributors and discussing about the issues on discord with them sir .so from now onwards I can assure you that there will be multiple contributors contributing to our repo sir . Assigning levels to prs for most of the prs if they are worth for the level then only iam assigning levels but if there are some changes regarding assigning of levels I will make sure from onwards I will very more careful regarding those things .
Iam sorry regarding the spams in repo sir . I will not repeat those things again sir .
Thank you sir .

**Comment by sanjay-kv** [comment]
image

Im just curious over here, i can only see readme changes. can u provide the links to the actual deployment ?

**Comment by Ansh101112** [comment]
> image
> 
> Im just curious over here, i can only see readme changes. can u provide the links to the actual deployment ?
> 

Here's the live link: https://esmart-github-io.vercel.app/

**Comment by sanjay-kv** [comment]
yes, but i could see you already created 2 to 3 deployment PR. 
and this its a reademe change. and I don't see any other changes. 

So provide necessary link made here.

**Comment by Ansh101112** [comment]
okay sir. In repo I have fixed the bug and added these lines of code at that time here's the repo ss. Also sir that repo is on my account so I am directly managing the REPO without raising any pr over that repo. BTW here's the code proof:

const authenticateUser = (req, res, next) => {
  const token = req.headers.authorization;

  if (!token) {
    return res.status(401).json({ message: "Authorization token is required" });
  }

  try {
    const decoded = jwt.verify(token.split(" ")[1], process.env.JWT_SECRET);
    req.user = decoded;
    next();
  } catch (error) {
    return res
      .status(401)
      .json({ message: "Invalid authorization token. Login Again" });
  }
};

// TEST API
app.get("/", (req, res) => {
  res.status(200).send("Server started.");
});

// API to delete user account
app.delete("/delete", authenticateUser, async (req, res) => {
  try {
    const userId = req.user.userId;
    const deletedUser = await User.findByIdAndDelete(userId);

    if (!deletedUser) {
      return res.status(404).send({ message: "User not found" });
    }

    res.status(200).send({ message: "User deleted successfully" });
  } catch (error) {
    console.error(error);
    res.status(500).send({ message: "Server error" });
  }
});

// API FOR NOTIFICATION SETTINGS

// Ensure the phone number is in E.164 format
const formatPhoneNumber = (phoneNumber) => {
  if (phoneNumber.startsWith("+")) {
    return phoneNumber;
  }
  // Assuming all phone numbers are from India for this example
  const countryCode = "+91";
  return countryCode + phoneNumber;
};
These lines of code I have added in the backend code repo during this pr raised thats' why

**Comment by Ansh101112** [comment]
And also sir I have made the further changes on the server from the railway to render for deployment and also manages all the bug that occurred during the deployment Hence you have only seen the frontend changes and doesn't consider my hard work regarding the same project other repo that consist of the backend server side tasks.
Please do understand sir all the labels provided to me are managed and thoroughly checked by reviewers as well by PA before giving any label to my PRs.

**Comment by sanjay-kv** [comment]
> So provide necessary link made here.

@Ansh101112 I said links to the PR you made respective to this issue. 

I can get random code and paste in a issue like this as well. As a reviewer I wont be having time to understand the entire workflow of the project by looking at the code. So PR links is requested for the same purpose. 

I will pass to my technical team and get the review done.

**Comment by Ansh101112** [comment]
> > So provide necessary link made here.
> 
> @Ansh101112 I said links to the PR you made respective to this issue. 
> 
> I can get random code and paste in a issue like this as well. As a reviewer I wont be having time to understand the entire workflow of the project by looking at the code. So PR links is requested for the same purpose. 
> 
> I will pass to my technical team and get the review done. 
> 
> Also @usha-madithati how can you let the user manage organisational project from personal repo, this can cause depended issue later. what if the contributor goes offline and something is broken on your website. 
> 
> I don't see anyone else doing the same in the program. No personal repos is counted towards contribution. Now its looks like I have to review all his contributions. 
> 
> + I don't understand the point you mentioned below. 
> image
> 

Sir please see the reply where I have mentioned you in the previous reply discussion

**Comment by Ansh101112** [comment]
> > So provide necessary link made here.
> 
> @Ansh101112 I said links to the PR you made respective to this issue. 
> 
> I can get random code and paste in a issue like this as well. As a reviewer I wont be having time to understand the entire workflow of the project by looking at the code. So PR links is requested for the same purpose. 
> 
> I will pass to my technical team and get the review done. 
> 
> Also @usha-madithati how can you let the user manage organisational project from personal repo, this can cause depended issue later. what if the contributor goes offline and something is broken on your website. 
> 
> I don't see anyone else doing the same in the program. No personal repos is counted towards contribution. Now its looks like I have to review all his contributions. 
> 
> + I don't understand the point you mentioned below. 
> image
> 

And sir the points that I am saying is that the backend repo is on my account so I am directly pushing the code to codebase without raising any PRs

**Comment by usha-madithati** [comment]
> > So provide necessary link made here.
> 
> @Ansh101112 I said links to the PR you made respective to this issue. 
> 
> I can get random code and paste in a issue like this as well. As a reviewer I wont be having time to understand the entire workflow of the project by looking at the code. So PR links is requested for the same purpose. 
> 
> I will pass to my technical team and get the review done. 
> 
> Also @usha-madithati how can you let the user manage organisational project from personal repo, this can cause depended issue later. what if the contributor goes offline and something is broken on your website. 
> 
> I don't see anyone else doing the same in the program. No personal repos is counted towards contribution. Now its looks like I have to review all his contributions. 
> 
> + I don't understand the point you mentioned below. 
> image
> 

Sir @sanjay-kv  when I have asked him about that he told that he will be much more comfortable to work from his repo and then merge those files to our repo .yes sir I understand your concern, I will not let him do that again sir. From now on he will do everything from the main repo itself sir .

**Comment by sanjay-kv** [comment]
> Sir please see the reply where I have mentioned you in the previous reply discussion

This the problem @Ansh101112 , Everything is messed up here. 

When we are in a program we should follow rules and guidelines. Any further activities you done beyond the guidelines should communicate well before the the core team for eg. managing repo on your personal account. 

Now you telling me you pasted the proof of work done in the previous PR which has some issue. i thought those PR where respective to the Proof done to that work,

So I'm pretty much confused over whats going on. 
image
image

**Comment by sanjay-kv** [comment]
We will be discussing on the respective PR itself. 

I have given technical team to review it. lets wait until it finish

**Pull request merged**
