### PR TITLE
Made the nave bar Sticky

### LINKED ISSUE #463: Feat:Sticky Nav Bar
### Describe the feature

Making The nav bar sticky

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by Saipradyumnagoud**
Closes #463

### CODE REVIEW

**Comment by Saipradyumnagoud** [comment]
@usha-madithati Can you Please Review the pull Request Soon,so that i can work on your repo again

**Comment by Saipradyumnagoud** [comment]
@usha-madithati are there any changes to be made

**Comment by usha-madithati** [comment]
I will check and tell you

**Comment by Saipradyumnagoud** [comment]
> I will check and tell you

Can You Please Review it today soon mam,so that i get updated in the leaderboard

**Comment by Saipradyumnagoud** [comment]
image

it is working

**Comment by Saipradyumnagoud** [comment]
@usha-madithati It is working but i dont why are you  not able to see the changes

**Comment by usha-madithati** [comment]
Send me the screen shot

**Comment by Saipradyumnagoud** [comment]
image

@usha-madithati This is the Screenshot

**Comment by Saipradyumnagoud** [comment]
@usha-madithati It is working in the website also please check once

**Comment by usha-madithati** [comment]
Yeah ok . Its working fine.

**Comment by Saipradyumnagoud** [comment]
@usha-madithati yes

**Pull request merged**
